version: '3.8'

services:
  avito-shop-service:
    build:
      context: .
      dockerfile: avito-shop-service/Dockerfile
    volumes:
      - ./avito-shop-service:/app
    ports:
      - "8800:8800"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PROJECT_NAME=${PROJECT_NAME}
    networks:
      - shop-network

  db:
    image: postgres:13
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - shop-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locustfile.py:/locust/locustfile.py
    environment:
      - LOCUST_HOST=http://avito-shop-service:8800
    depends_on:
      - avito-shop-service
    networks:
      - shop-network
    command: -f /locust/locustfile.py --host ${LOCUST_HOST:-http://avito-shop-service:8800}


volumes:
  postgres_data:

networks:
  shop-network:
    driver: bridge
